### PR TITLE
add persist storage to prometheus

### PR DESCRIPTION
**Pull request by yacut**
related to https://github.com/istio/istio/pull/18740

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
/ok-to-test

**Comment by sdake** [comment]
@yacut you will need to run `make gen` with BUILD_WITH_CONTAINERS=1.  It may be necessary to unset your HUB and TAG environment variables if they are set (although I believe @howardjohn fixed that problem).

`make gen` will trigger the generation of binary blobs from the source manifests in the repository.

Cheers
-steve

**Comment by sdake** [comment]
@howardjohn I am of the opinion that we should punt the third party component install to the upstreams and instead focus on integration with the third-party components.  For this specific issue, you had pointed at a path to integration, and @douglas-reid had indicated that path was not going to happen in 1.5 :grin:

As such, I feel we should just freeze any changes to third party components (unless they involve the resolution of a security vulnerability or general image update) until such time as we can produce an RFC and obtain a sign off or rejection of the RFC from the telemetry WG.

I'll produce the RFC this afternoon.

Cheers
-steve

**Comment by johscheuer** [comment]
I agree with @sdake also most "production" installations will already have their Prometheus/Grafana  installation somehow managed and just putting Istio on top of it (at least in my experience) and the Installer should refer to the official installation docs of the specific tools and just document how to integrate them (or provide some basic dashboards/alerts/..).

**Comment by adamrbennett** [comment]
@sdake @johscheuer Has an official position been taken with regard to third party components? It sounds like the sentiment here is that out-of-the-box third-party component integration is generally not supported for non-trival use-cases.

**Comment by sdake** [comment]
@adamrbennett yes a decision has been made for third party components. The decision, as I understand it, is that Istio will provide documentation on istio.io that describes how to integrate with third party components that make sense for Istio to integrate with, assuming there is someone to maintain said integration.

For more context, please review this heavily debated and agreed upon plan and design:

https://docs.google.com/document/d/1jJ4kkALCUPWIlz_Ldu6jpeelMNxyY_SZDMaZmeSpfkM/edit#heading=h.qlmnvhzb2ib2

**Comment by sdake** [comment]
This PR has been subsumed by https://docs.google.com/document/d/1jJ4kkALCUPWIlz_Ldu6jpeelMNxyY_SZDMaZmeSpfkM/edit#heading=h.qlmnvhzb2ib2. If you disagree, please reopen the issue.

Cheers,
-steve

**Pull request closed without merging**
