### PR TITLE
Support grpc response (mapped to http code) in logs and metrics

### PR DESCRIPTION
**Pull request by djazayeri**
Addressing https://github.com/istio/istio/issues/2704

Depends on https://github.com/istio/istio/pull/14186

Still needs testing (and I don't yet know where to put them).

/hold

### CODE REVIEW

**Comment by howardjohn** [comment]
Just adding do not merge since it is blocked by the istio change

**Comment by costinm** [comment]
What is the status on this ?

**Comment by douglas-reid** [comment]
@costinm I believe this needs to be updated based on the approved design from the last P&T WG meeting.

**Comment by djazayeri** [comment]
We changed our approach (https://discuss.istio.io/t/supporting-grpc-in-telemetry/2616/2)
So closing this.

**Pull request closed without merging**
