### PR TITLE
remove namespace for meshpolicy.

### PR DESCRIPTION
**Pull request by morvencao**
remove namespace for cluster scoped resource: `MeshPolicy`.

### CODE REVIEW

**Comment by costinm** [comment]
Wait a minute, when did we end up with a cluster wide resource ? Is it alpha or beta ? Approved ? 

This has major implications on new installer - the main point is to be able to make safe upgrades, without a global change that can bring down the entire cluster.

**Comment by costinm** [comment]
I would rather remove the 2 MeshPolicies from installer - and make it clear users should probably not use them, and if they do it's not installer's fault. 

/hold

**Comment by morvencao** [comment]
@costinm The `meshPolicy` api is still in alpha, not sure if these changes will block upgrade, I can give it a try.

**Comment by costinm** [comment]
I think the best option is to try to get rid of the MeshPolicy from new installer. If user wants to use them - they can, but the goal is to avoid 'cluster wide' / 'global' changes.

**Pull request merged**
