### PR TITLE
Remove mount of docker as it's part of new kind image

### PR DESCRIPTION
**Pull request by ericvn**

### CODE REVIEW

**Comment by howardjohn** [comment]
You can remove the label when all tests are passing, we need to update mergify to require all the tests now that they should all pass.

But looks like they are failing from missing docker

**Comment by ericvn** [comment]
It looks like the `istionightly/kind:v1.14.1-1` might not have been after https://github.com/istio/installer/pull/103. Checking that now.

**Comment by howardjohn** [comment]
I think it is manually built by costin

**Comment by ericvn** [comment]
Looks like it wasn't built again after #103 was merged. Will work with costing to get that pushed.

Locally built image:
```
# ls /usr/local/bin
ci2gubernator  clean-install  crictl  ctr  docker  entrypoint  go-junit-report	helm  istioctl	kind  repo
```
Currently checked in image:
```
# ls /usr/local/bin
ci2gubernator  clean-install  crictl  entrypoint  go-junit-report  helm  istioctl  kind  repo
```

**Pull request merged**
