### PR TITLE
Turn off DNS certificate provisioning

### PR DESCRIPTION
**Pull request by lei-tang**
This PR is for the issue: https://github.com/istio/istio/issues/18456

### CODE REVIEW

**Review by linsun — APPROVED** [review]
Thanks @lei-tang

**Comment by sdake** [comment]
Thanks, @lei-tang.  I'll see if I can sort out if the gate is broken this morning and get it moving for your work start.

Cheers
-steve

**Comment by sdake** [comment]
@lei-tang - try the following prior to running `make gen`

````
unset HUB
unset TAG
```
and then `make gen`

and commit the changes.

Cheers
-steve

**Comment by lei-tang** [comment]
Thanks! I have pushed a commit with the changes after unsettings and "make gen".

**Comment by linsun** [comment]
@lei-tang can you manually generate a 1.4 PR for this?

**Comment by lei-tang** [comment]
@linsun The cherrypicking PR on release 1.4 is https://github.com/istio/installer/pull/474.

**Pull request merged**
