### PR TITLE
Allow set lifecycle to sidecar template

### PR DESCRIPTION
**Pull request by k0da**
Signed-off-by: Dinar Valeev <k0da@opensuse.org>

### CODE REVIEW

**Review by richardwxn — COMMENTED** [review]
You may need to add lifecycle to the values.yaml as well

**Comment by k0da** [comment]
> You may need to add lifecycle to the values.yaml as well
done

**Comment by k0da** [comment]
@richardwxn any other review comments?

**Comment by richardwxn** [comment]
for your values.yaml file definition, I think the lifecycle section is a map not an array?

**Comment by k0da** [comment]
@richardwxn right, lifecycle is a map

**Review by richardwxn — APPROVED** [review]

**Pull request merged**
