### PR TITLE
Make number of certmanager replicas configurable

### PR DESCRIPTION
**Pull request by Lysholm**
This fixes: https://github.com/istio/istio/issues/14380

### CODE REVIEW

**Comment by wattli** [comment]
CertManager does not interact with Citadel directly. As long as the multiple instances do not have conflict when generating secrets, then it should be good.

**Comment by Lysholm** [comment]
@howardjohn: certmanager has had leader election since 2017: https://github.com/jetstack/cert-manager/pull/42.

I've been scaling it up since i started using it about a year ago. The non leader only has this in it's logs:
```
I0528 09:54:46.234790       1 start.go:81] starting cert-manager v0.6.2 (revision f5e1477bd7ced69e53a233484905fea16bf4102f)
I0528 09:54:46.255302       1 controller.go:141] Using the following nameservers for DNS01 checks: [10.0.0.10:53]
I0528 09:54:46.256696       1 leaderelection.go:193] attempting to acquire leader lease  istio-system/cert-manager-controller...
```
So i think it's safe but i haven't tested it extensively.

**Comment by wattli** [comment]
In general i think it should be fine, but keep in mind, leaderelection does not guarantee conflict free https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L19

**Comment by Lysholm** [comment]
> In general i think it should be fine, but keep in mind, leaderelection does not guarantee conflict free https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L19

I was not aware of that, thanks!

**Comment by linsun** [comment]
@morvencao sorry I didn't see this earlier, looks like cert mgr ok for replica 1+.  We probably want to revert your PR on PDB for it, WDYT?

**Comment by morvencao** [comment]
@linsun I did see this PR, either.  I'm OK to add back PDB for cert-manager if its replicas is configurable.

**Pull request merged**
