### PR TITLE
Register new RequestAuthentication API

### PR DESCRIPTION
**Pull request by diemtvu**
Update the `crd-all.gen.yaml` with the new one generated from https://github.com/istio/istio/pull/18949. 

This change is needed to fix `integ-new-install-k8s-tests_istio` for that PR.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
/retest

This is a bug in the CI, I am working on fixing.

**Comment by diemtvu** [comment]
Looks like it's persisted. What I can see is the `kustomize/cluster/crds-namespace.gen.yaml` may need to add the new CRD as well? However, I don't know what is the right command to regenerate it. `make gen` create a big changes in my local repo.

**Comment by howardjohn** [comment]
@diemtvu I will make sure this gets fixed

**Pull request merged**
