### PR TITLE
Update kustomize templates

### PR DESCRIPTION
**Pull request by ConcourseWdf**
This PR is created automatically!

### CODE REVIEW

**Comment by jkbschmid** [comment]
@geeknoid @howardjohn 
Is there a way to give this bot clearance for the CLA-agreement?

**Comment by jkbschmid** [comment]
Side note: Install-demo fails because the make-target creates an invalid test/demo/k8s.yaml, so this failure is kind of '_intended_' for this PR.

**Comment by geeknoid** [comment]
No sorry, that's against corporate policy because it could be used to subvert the CLA process and sneak in some non-CLAed changes. So PRs generated by this bot will need manual review.

Could this be run as part of the build process instead?

**Comment by howardjohn** [comment]
@geeknoid the reason we have the generated files in the repo is so users can do things like `kubectl -k github.com/istio/install/...` and install Istio in one command

**Comment by geeknoid** [comment]
It's fine to have the generated files checked in. But can these just be
checked in as part of a human doing a local build and commit, like we do in
the API repo?

**Comment by c0d1ngm0nk3y** [comment]
How to continue with this PR? I see 4 options

1) To keep it a manual process to sync those files (not really an option IMHO)
2) Use a CI to update those files automatically (like proposed in this PR), but opens some questions with the CLA bot.
3) To integrate it in the build process (make), so that it is at least hard to get those files out-of-sync.
4) Do not checkin generated files in the first place. @howardjohn I see your use case with the `one command install`, but would't it be an option to generate and add those files in the release process? That sounds more natural to me.

I would prefer option 4. @howardjohn Do you think that could be an option?

**Comment by geeknoid** [comment]
Assuming generating those files isn't a terrible burden, not checking in
generated files is definitely preferable.

**Comment by holgero** [comment]
@c0d1ngm0nk3y If we go for option 4 (generate the files in a release build), it would be no longer a one step installation from master. OTOH, I am not sure if we really need that option (of a one-step-installation from current master). Maybe it is even better this way, so that customers are directed to the released versions. And for developers it should be a reasonable request, that they have to generate the files by themselves first.

**Pull request closed without merging**
