### PR TITLE
Move up grafana to latest

### PR DESCRIPTION
**Pull request by linsun**
I did a quick testing of 6.4.3 with 1.4 beta 2, didn't notice any issues.

### CODE REVIEW

**Comment by sdake** [comment]
looks fine once you run `make gen`.  You may need to unset HUB and TAG if they are set in your enviornments ot run `make gen.

**Comment by howardjohn** [comment]
This is only modifying the generate files not the source of those files. The source of truth is something like istio-telemetry/grafana/values.yaml

**Comment by linsun** [comment]
@howardjohn @sdake thanks, didn't realize the files were generated. PTAL.

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
