### PR TITLE
Update inject-template.yaml

### PR DESCRIPTION
**Pull request by crazyxy**
Backport changes from https://github.com/istio/istio/pull/13801

### CODE REVIEW

**Comment by costinm** [comment]
Adding a do-not-merge ( /hold doesn't work ) - waiting for the nightly and we'll need to rebuild the base builder image so istioctl has the change.

**Comment by costinm** [comment]
Removed the do not merge - if the test pass (i.e. everything was updated ) looks good.

**Comment by howardjohn** [comment]
@crazyxy sorry for the delays on this, can you rebase? should be fixed now

**Pull request merged**
