### PR TITLE
Add back NodePort 31380 31390

### PR DESCRIPTION
**Pull request by clyang82**
To keep consistence with istio/istio. I should be able to access the bookinfo example by using 31380 port.

Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

### CODE REVIEW

**Review by howardjohn — CHANGES_REQUESTED** [review]
having fixed node ports has caused a lot of problems as they need to be globally unique. I don't think we should add these back.

Is there a good reason to add this?

**Comment by clyang82** [comment]
we have defined nodeport in istio/istio with 31380 and 31390 https://github.com/istio/istio/blob/1aeca5f2bd3619072dc522574fc81825ac32d897/install/kubernetes/helm/istio/charts/gateways/values.yaml#L66 and the document claims the default value as well -https://istio.io/docs/reference/config/installation-options/
but it does not work in istio/installer. I think we should keep the same behaviour. WDYT?

**Comment by howardjohn** [comment]
The goal of istio/installer is not to replicate all of the functionality of the old one, but to improve on it. In my opinion adding it in the other installer was a mistake that I don't think we should replicate here, unless there is a good reason to

**Comment by clyang82** [comment]
OK. Thanks for your comments. Let me close it until there is a good reason.

**Pull request closed without merging**
