### PR TITLE
Revert "auto mtls on by default (#446) (#452)"

### PR DESCRIPTION
**Pull request by howardjohn**
This reverts commit 1ee2c9007de2adc84d5f03fb898920603cbfcce4.

### CODE REVIEW

**Comment by ericvn** [comment]
Do we also need to change /test/demo/values.yaml as done in #455?

**Comment by howardjohn** [comment]
good catch

**Comment by ostromart** [comment]
Hi @jwendell @ericvn @howardjohn could we get this merged soon so I can sync the operator charts?
Thanks in advance!

**Comment by howardjohn** [comment]
@ostromart if its blocking you could submit the same exact PR and I can approve it.. if not one of them should get to it soon/tomorrow

**Review by ericvn — APPROVED** [review]

**Pull request merged**
