### PR TITLE
add istio-reader clusterrole to access remote clusters with reduced privileges

### PR DESCRIPTION
**Pull request by ayj**
This also fixes an issue where mixer doesn't have sufficient access to
read replicationcontrollers in remote clusters.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Why is this in pilot's charts if this is about mixer?

**Comment by ayj** [comment]
It's shared between pilot and mixer. Both can use the same service account when accessing remote clusters. I added it to pilot since this was more likely to be enabled even in minimal profiles. Is there a different general charts directory that would be more appropriate?

**Comment by ayj** [comment]
One of the ingress-gateway pods failed to initialization. I don't think this is caused by adding the new clusterrole.

```
2019-11-05T22:12:07.426590143Z stdout F 2019-11-05T22:12:07.426304Z	warn	config status timed out. using last known values cds status: 12477129279942061858,lds status: 12477129279942061858
2019-11-05T22:12:08.926649544Z stdout F 2019-11-05T22:12:08.926305Z	warn	config server state timed out. using last known state LIVE
2019-11-05T22:12:09.526562221Z stdout F 2019-11-05T22:12:09.526350Z	warn	config status timed out. using last known values cds status: 12477129279942061858,lds status: 12477129279942061858
2019-11-05T22:12:11.426743285Z stdout F 2019-11-05T22:12:11.426469Z	warn	config status timed out. using last known values cds status: 12477129279942061858,lds status: 12477129279942061858
2019-11-05T22:12:12.427034084Z stdout F 2019-11-05T22:12:12.426781Z	warn	config server state timed out. using last known state LIVE
2019-11-05T22:12:13.42656628Z stdout F 2019-11-05T22:12:13.426304Z	warn	config status timed out. using last known values cds status: 12477129279942061858,lds status: 12477129279942061858
2019-11-05T22:12:14.826716353Z stdout F 2019-11-05T22:12:14.826443Z	warn	config server state timed out. using last known state LIVE
2019-11-05T22:12:15.526662266Z stdout F 2019-11-05T22:12:15.526419Z	warn	config status timed out. using last known values cds status: 12477129279942061858,lds status: 12477129279942061858
2019-11-05T22:12:16.826582272Z stdout F 2019-11-05T22:12:16.826286Z	warn	config server state timed out. using last known state LIVE
2019-11-05T22:12:17.726745429Z stdout F 2019-11-05T22:12:17.726452Z	warn	config status timed out. using last known values cds status: 12477129279942061858,lds status: 12477129279942061858
```

**Comment by howardjohn** [comment]
from https://github.com/istio/istio/issues/18665. Should probably revert
some PRs that caused this

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
