### PR TITLE
Add stackdriver tracing options to istio/installer

### LINKED ISSUE #18680: Stackdriver Tracing: incorrect env vars
When annotation and attribute params are not set, the template inserts `nil` thereby injecting an env var with value = `nil`.

The following was obtained by doing kubectl describe pods

```
     STACKDRIVER_TRACING_ENABLED:                       true
      STACKDRIVER_TRACING_DEBUG:                         false
      STACKDRIVER_TRACING_MAX_NUMBER_OF_ANNOTATIONS:     nil
      STACKDRIVER_TRACING_MAX_NUMBER_OF_ATTRIBUTES:      nil
      STACKDRIVER_TRACING_MAX_NUMBER_OF_MESSAGE_EVENTS:  nil
```

### PR DESCRIPTION
**Pull request by gargnupur**
Fixes https://github.com/istio/istio/issues/18680

### CODE REVIEW

**Review by mandarjog — APPROVED** [review]
Change looks ok.

Why are there two templates one in control and one in discovery?

**Comment by gargnupur** [comment]
@mandarjog : looks like discovery one's are newer.. not sure why.. @howardjohn might know?

**Review by richardwxn — APPROVED** [review]

**Comment by richardwxn** [comment]
the injection templates in discovery is for istiod?

**Comment by bianpengyuan** [comment]
@gargnupur Could you cherry-pick this as well as the env variable integer value fix into 1.4? Thanks!

**Comment by gargnupur** [comment]
@bianpengyuan : env variable integer value fix is already in 1.4

Requesting this one to 1.4 too

**Pull request merged**
