### PR TITLE
Add milliseconds duration to dashboard

### PR DESCRIPTION
**Pull request by bianpengyuan**

### CODE REVIEW

**Comment by mandarjog** [comment]
can you add a link to an exported dashboard showing this at work?

**Comment by bianpengyuan** [comment]
mesh: https://snapshot.raintank.io/dashboard/snapshot/3J0i1zMhKRr54iQWchmR7SDnJIq6MJrc
workload: https://snapshot.raintank.io/dashboard/snapshot/gpmaOtGDrxeD63bKUEnSXL9bKg8gGknp
service: https://snapshot.raintank.io/dashboard/snapshot/x29FrzqKkEkNltjGQ09n7U3rsD040W6c

**Review by douglas-reid — APPROVED** [review]
/lgtm

Do we want this in istio/istio as well?

**Comment by bianpengyuan** [comment]
@douglas-reid yes it is already there: https://github.com/istio/istio/pull/16859

**Comment by bianpengyuan** [comment]
@istio/wg-environments-maintainers Ping, please help to take a look at this. Thanks!

**Review by ayj — APPROVED** [review]

**Pull request merged**
