### PR TITLE
Update grafana-dashboard for syncing with istio/istio install k8s

### PR DESCRIPTION
**Pull request by carolynhu**
This PR is to make sure that the changes to the grafana dashboard in istio/istio have been fully ported over to the new installer (istio/installer).

TODO:
I will update the test here asap.

### CODE REVIEW

**Comment by howardjohn** [comment]
Thank you!

**Comment by howardjohn** [comment]
@carolynhu can you sign the CLA?

**Comment by carolynhu** [comment]
@howardjohn when I click the sign cla link, it shows "Googlers do not need to sign a CLA. If you are having trouble contributing to a Google open source project, see go/cla#googlers or email signcla-users@." Does this mean the corp has signed it for me?

**Comment by carolynhu** [comment]
@googlebot I signed it!

**Comment by howardjohn** [comment]
I think the test failures may he fixed by s recent pr if you could rebase?

**Pull request merged**
