### PR TITLE
Kill gen

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Review by richardwxn — COMMENTED** [review]
Are we going to still keep the kustomize directory and the corresponding kustomization files but just remove the gen files

**Comment by howardjohn** [comment]
@richardwxn yes they are generate at test time

**Comment by howardjohn** [comment]
Maybe not long term

**Review by sdake — APPROVED** [review]
LGTM.

**Comment by richardwxn** [comment]
@howardjohn you can also remove the whole run-build-default target

**Comment by costinm** [comment]
Not very happy with this - kubectl apply -k without downloads was very convenient and is what K8S recommends for installs.

I will continue to maintain kustomize templates in a private repo for now. 

Keep in mind people use CI/CD and other ways to install istio - and we want to move away from helm dependency ( operator is just using helm with same complex templates ).

**Pull request merged**
