### PR TITLE
Support customized labels for istio-ingress

### PR DESCRIPTION
**Pull request by clyang82**
sub-task of https://github.com/istio/istio/issues/19860
Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>

### CODE REVIEW

**Review by morvencao — COMMENTED** [review]
You may also need to update the service selector so that it can select the correct pods, see: https://github.com/istio/installer/blob/master/gateways/istio-ingress/templates/service.yaml#L28-L29

**Review by morvencao — COMMENTED** [review]
do we need to make the same changes to istio-egressgateway?

**Comment by clyang82** [comment]
> You may also need to update the service selector so that it can select the correct pods, see: https://github.com/istio/installer/blob/master/gateways/istio-ingress/templates/service.yaml#L28-L29

Yes. Good catch. Let me update the PR. Thanks.

**Comment by elfinhe** [comment]
error: timed out waiting for the condition on deployments/istio-ingressgateway

**Review by elfinhe — APPROVED** [review]

**Comment by elfinhe** [comment]
@morvencao PTAL to double check.

**Comment by morvencao** [comment]
/LGTM
@clyang82 Can you check why the test failed?

**Review by morvencao — COMMENTED** [review]
/LGTM
@clyang82 Can you check why the test failed?

**Comment by clyang82** [comment]
the failed test was fixed in https://github.com/istio/istio/pull/20041

**Pull request merged**
