### PR TITLE
add missing pod annotations parameter to istio charts.

### PR DESCRIPTION
**Pull request by morvencao**
merge https://github.com/istio/istio/pull/16886

### CODE REVIEW

**Comment by clyang82** [comment]
Do we need to have a default `podAnnotations` in global.yaml?

**Comment by howardjohn** [comment]
This is a perfect use case for kustomize or operator overlay. Do we need to
add another API for this?

**Comment by morvencao** [comment]
@howardjohn Istio operator API already support this in k8s overlay, see: https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto#L437-L439

**Comment by howardjohn** [comment]
Great to see. If we can support this via kustomize and operator I don't think we should add this to helm values. I believe the goal is to aggressively reduce the amount of config exposed by values.yaml?

**Comment by morvencao** [comment]
@clyang82 not yet, currently many global values, eg. `defaultToleration`, `defaultNodeSelector` haven't been translated to operator API, we may don't want to add another field like that, let's keep it in each single chart.

**Review by costinm — APPROVED** [review]

**Pull request merged**
